#!/usr/bin/perl

use 5.010_000;
use strict;
use warnings;

BEGIN {

    # will eventually check for mplayer on all platforms...
}

use Getopt::Long qw/:config no_ignore_case /;
use Pod::Usage;
use Cwd qw/ realpath /;

my $VERSION = '1.0.0';

__END__

=head1 SYNOPSIS

<file/device> <-o file.mp4> [options]

Options:

  -h, -?, --help  This help / usage screen...
  -o, --output    Output file name...
  -v, --vbit      Video bitrate to use...
  -a, --abit      Audio bitrate to use...
  -x, --scale     Video scale to use...
  -p, --pass      Number of passes to use...
  -t, --threads   How many threads to use...
  -m, --mencoder  Additional MEncoder options...

Example: mcode dvd://1 -o file.mp4 -m "-af volume=10"

=cut
