#!/usr/bin/env perl

use 5.010_000;
use strict;
use warnings;

use Getopt::Long qw/:config no_ignore_case /;
use Pod::Usage;
use File::Basename;

my %obj;

GetOptions(

    'length|l=f'   => \$obj{options}->{'length'},
    'split|s=i'    => \$obj{options}->{'split'},
    'mencoder|m=s' => \$obj{options}->{'mencoder'},
    'help|?|h'     => \$obj{options}->{'help'},
);

pod2usage "\nMUTATE :: File Splitter\n"
  if defined $obj{options}->{help}
      or not $ARGV[0];

if ("@ARGV" =~ /^\w+:\/\/\d+|\w+$/g) {

    eval { $obj{options}->{'input'} = realpath("@ARGV") };
    $obj{options}->{'input'} = "@ARGV" if $@;

    my $duration = $obj{options}->{'length'} / $obj{options}->{'split'};

    my $output = basename($obj{options}->{'input'});
    my $start  = 0;

    for (1 ... $obj{options}->{'split'}) {

        open my $mencoder,

          "mencoder \"$obj{options}->{'input'}\" -o $output-part$_ "
          . "-oac copy -ovc copy -ss $start -endpos $duration 2> split.err |";

        print while <$mencoder>;
        close $mencoder;

        $start += $duration;
    }
    unlink 'split.err' and exit(0);

}
else {

    say 'An MPlayer compatible File/Device must be clearly defined.'
      and exit(1);
}

exit(0);

__END__

=head1 SYNOPSIS

<file/device> <-s N> <-l N> [options]

Options:

  -h, -?, --help  This help / usage screen...
  -l, --length    Total length of the input file in seconds...
  -s, --split     The amount of times to split...
  -m, --mencoder  Additional MEncoder options...


Example: mutate split file.avi -l 5800.544 -s 15

=cut
