#!/usr/bin/env perl

use 5.010_000;
use strict;
use warnings;

use IO::Compress::Gzip qw/ gzip $GzipError /;
use IO::Compress::Zip qw/ zip $ZipError /;

use Getopt::Long qw/:config no_ignore_case /;
use Pod::Usage;
use File::Find;

my %obj;

GetOptions( 'help|?|h' => \$obj{options}->{'help'} );

pod2usage "\nMUTATE :: Subtitles\n"
  if defined $obj{options}->{help}
      or not $ARGV[0];

__END__

=head1 SYNOPSIS

"command line" [options]

Options:

  -h, -?, --help  This help / usage screen...

Example: mutate sub "command line"

=cut
