#!/usr/bin/perl
# msub (c) 2007 - 2009 MUTATE Video Encoding Tools

use 5.010_000;
use warnings;
use strict;

BEGIN { 

    # will eventually check for mplayer/mencoder/gzip/zip on all platforms...
}

use IO::Compress::Gzip qw/ gzip $GzipError /;
use IO::Compress::Zip qw/ zip $ZipError /;
use Getopt::Long qw/:config no_ignore_case /;
use Pod::Usage;

my $VERSION = '0.0.1';

__END__

=head1 SYNOPSIS

<file/device> <-o file> [options]

Options:

  -h, -?, --help  This help / usage screen...
  -o, --output    Output file name...
  -l, --lang      Video bitrate to use...
  -m, --mplayer   Additional MPlayer options...

Example: mcode dvd://1 -o file.mp4 -m "-af volume=10"

=cut
