#!/usr/bin/env perl

use 5.010_000;
use strict;
use warnings;

BEGIN {

    return if defined $ARGV[0] and $ARGV[0] =~ /daemon/x;

    system "$ENV{MUTATE_HOME}/toolkit/$ARGV[0]"
      if defined $ARGV[0]
          and $ARGV[0] =~ /\w+/x;

    exit(0)
}

use local::lib 'lib';

use Mojolicious::Lite;

# Increase limit to 1TB
$ENV{MOJO_MAX_MESSAGE_SIZE} = 1073741824000000000000;

any '/upload' => sub {
    my $self = shift;
    if (my $example = $self->req->upload('example')) {
        my $size = $example->size;
        my $name = $example->filename;

        $example->move_to('/tmp/video.in');

        $self->render(text => "Thanks for uploading $size byte file $name.");
    }

    open my $encode, "mutate video video.in -o video_out.avi -m '-ss 100 -endpos 30' |";
    close $encode;

};

app->start;

__DATA__

@@ upload.html.ep
<!doctype html><html>
    <head><title>Upload</title></head>
    <body>
    <%= form_for upload =>
	    (method => 'post', enctype => 'multipart/form-data') => begin %>
	<%= file_field 'example' %>
	<%= submit_button 'Upload' %>
    <% end %>
    </body>
</html>
