#!/usr/bin/env perl

use 5.010_000;
use strict;
use warnings;

BEGIN {

    return if defined $ARGV[0] and $ARGV[0] =~ /daemon/x;

    system "$ENV{MUTATE_HOME}/toolkit/@ARGV"
      if defined $ARGV[0]
          and $ARGV[0] =~ /\w+/x;

    exit(0)
}

use Mojolicious::Lite;

$ENV{MOJO_MAX_MESSAGE_SIZE} = 10000000000;

any '/upload' => sub {

    my $self = shift;
    
	if (my $example = $self->req->upload('example')) 
	{
        my $size = $example->size;
        my $name = $example->filename;

        $example->move_to('code.in');

        $self->render(text => "Thanks for uploading $size byte file $name.");

		my $pid=fork();
		die "Cannot fork: $!" if (! defined $pid);
		if (! $pid) {

			exec("$ENV{MUTATE_HOME}/toolkit/code code.in -o code.avi");
			exit();
		}
    }

};

app->start;

__DATA__

@@ upload.html.ep
<!doctype html><html>
    <head><title>Upload</title></head>
    <body>
    <%= form_for upload =>
	    (method => 'post', enctype => 'multipart/form-data') => begin %>
	<%= file_field 'example' %>
	<%= submit_button 'Upload' %>
    <% end %>
    </body>
</html>
