=pod

=encoding utf8

=head1 NAME

MUTATE Media Tools

=head1 SYNOPSIS

	mcode dvd://1 -o file.mp4 -m "-af volume=10"

=head1 DESCRIPTION

Mutate is a set of media tools written in Perl, and for use with MPlayer and MEncoder.

=head1 BUGS
	
	http://github.com/ispyhumanfly/mutate/issues

=head1 SEE ALSO
	
	http://wiki.github.com/ispyhumanfly/mutate/

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut

