=pod

=encoding utf8

=head1 NAME

MUTATE :: The A/V Toolkit for MPlayer

=head1 SYNOPSIS

	View information about your media...

	mscan ~/Music ~/Videos

	Create FFmpeg/MP3 movies from disc or file...

	mcode dvd://1 --output file.avi

	Partition your video or audio into multiple files...

	msplit file.avi --length 5800.540 --split 2

	Group multiple movies into a single file...

	mjoin file1.avi file2.avi --output file.avi

=head1 DESCRIPTION

MUTATE is a set of media tools written in Perl, and for use with MPlayer and MEncoder.

=head1 BUGS

	http://github.com/ispyhumanfly/mutate/issues

=head1 SEE ALSO

	http://wiki.github.com/ispyhumanfly/mutate/

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
