#!/usr/bin/env perl

use 5.010_000;
use strict;
use warnings;

use Getopt::Long qw/:config no_ignore_case /;
use Pod::Usage;

my %obj;

GetOptions(

    'output|o=s'   => \$obj{options}->{'output'},
    'mencoder|m=s' => \$obj{options}->{'mencoder'},
    'help|?|h'     => \$obj{options}->{'help'},
);

pod2usage "\nMUTATE :: Join Files\n"
  if defined $obj{options}->{help}
      or not $ARGV[0];

open my $mencoder,

  "mencoder @ARGV -o \"$obj{options}->{'output'}\" "
  . "-oac copy -ovc copy 2> join.err |";

print while <$mencoder>;
unlink 'join.err' and close $mencoder;

__END__

=head1 SYNOPSIS

<file/device> <-s N> <-l N> [options]

Options:

  -h, -?, --help  This help / usage screen...
  -o, --output    The name of the end result...
  -m, --mencoder  Additional MEncoder options...


Example: mutate join file1 file2 file3 -o file.avi

=cut
